"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MyWeather.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'iconfile': '/Users/james/MyWeather/icon/app.icns', 'includes': ['BeautifulSoup', 'getWeathers', 'GUI']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
